config/routes.rb
Rails.application.routes.draw do
  LOCALES = /en|pt\-BR/
  scope ":locale", :locale => LOCALES, :defaults => {:locale=> 'pt-BR'} do

    resources :rooms do
      resources :reviews, :only =>[:create, :update], :module => :rooms
    end
    resources :users

    resource :confirmation, :only => [:show]

    resource :user_sessions, :only => [:create, :new, :destroy]

    get 'users/:id/rooms' =>  'users#rooms', as: :user_rooms

  end

  get '/:locale' => 'home#index', :locale => LOCALES
  root 'home#index'

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  has_many :rooms, :dependent => :destroy
  has_many :reviews, :dependent => :destroy
  include BCrypt


  validates_presence_of :full_name, :location
  validates_length_of :bio, :minimum => 30, :allow_blank => false
  validates_uniqueness_of :email

  validates :email,
            :format => {:with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/},
            :presence => true

  scope :confirmed, -> {
    where('confirmed_at IS NOT NULL')
  }

  has_secure_password

  before_create :generate_token

  def generate_token
    self.confirmation_token = SecureRandom.urlsafe_base64
  end

  def confirm!
    return if confirmed?

    self.confirmed_at = Time.current
    self.confirmation_token = ''

    save!
  end

  def confirmed?
    confirmed_at.present?
  end

  def self.authenticate(email, password)
    confirmed.
        find_by(email: email).
        authenticate(password)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_authentication, :only => [:new, :create]
  before_filter :can_change, :only => [:edit, :update]
  before_filter :require_authentication, :only => :rooms

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, :notice => 'Cadastro criado com sucesso!'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user, :notice => "Update done!:)"
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:full_name, :email, :password, :password_confirmation, :location, :bio)
  end

  def can_change
    unless user_signed_in? && current_user == user
      redirect_to user_path(params[:id])
    end
  end

  def user
    @user ||= User.find(params[:id])
  end

  def rooms
    @rooms =  User.find(params[:id]).rooms.order('created_at desc') #  current_user.rooms.
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

    <% if @user.errors.any? %>
        <div id="error_explanation">
          <%= t 'general.form_errors'%>
        </div>

    <% end %>

    <p>
      <%= f.label :full_name %>
      <%= f.text_field :full_name %>
      <%= error_tag @user, :full_name %>

    </p>
    <p>
      <%= f.label :location %>
      <%= f.text_field :location %>
      <%= error_tag @user, :location %>
    </p>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= error_tag @user, :email %>
    </p>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= error_tag @user, :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
      <%= error_tag @user, :password_confirmation %>
    </p>
    <p>
      <%= f.label :bio %>
      <%= f.text_area :bio %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/users/edit.html.erb
<h1><%= t '.title'%></h1>

<%= render 'form' %>

<%= link_to "Voltar", @user %>

app/views/users/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>


<%= link_to (t 'links.back'), root_path %>

app/views/users/rooms.html.erb
<h1><%= t '.title' %></h1>

<% @rooms.each do |room| %>

    <article class="room">
      <h2><%= link_to room.title, room %></h2>
      <span class="created">
        <%= t '.owner_html',
              :owner => room.user.full_name,
              :when => l(room.created_at, :format => :short) %>
      </span>

      <p>
        <span class="location">
            <%= link_to room.location,
                        "http://maps.google.com/?q=#{room.location}",
                        :target => :blank %>
        </span>
      </p>

      <p><%= room.description %></p>
      <% if belongs_to_user(room) %>
          <ul>
            <li><%= link_to t('.edit'), edit_room_path(room) %></li>
            <li><%= link_to t('.destroy'), room_path(room), :method => :delete, :data => {:confirm => t('dialogs.destroy')} %></li>
          </ul>
      <% end %>

    </article>
<% end %>

app/views/users/show.html.erb
<h1><%= t '.title', :user_name => @user.full_name %></h1>

<ul>
  <li><%= t '.location', :location => @user.location %></li>
  <li> <%= t '.bio', :bio => @user.bio %> </li>
</ul>

<%= link_to t('.myrooms'), user_rooms_path %><br>
<%= link_to t('.edit'), edit_user_path(@user) %><br>
<%= link_to 'Home', root_path %>